/**
 * Year-scale analysis over an hourly simulation.
 *
 * The simulator already produces 8,760 values per series — generation,
 * consumption, self-use, import, export, battery flow, state of charge, cost
 * and tariff band. Almost none of that reached the reader. These functions
 * aggregate it into the shapes a person can actually reason about: months,
 * representative days, tariff bands, and the ratios that describe how well a
 * system fits the home it is attached to.
 *
 * All pure: they take arrays and return plain objects.
 */

import { DAYS_IN_MONTH, HOURS_IN_YEAR, type Band } from './constants.js';

export interface HourlySim {
  gen: Float32Array;
  cons: Float32Array;
  grid_import: Float32Array;
  grid_export: Float32Array;
  battery_charge: Float32Array;
  battery_discharge: Float32Array;
  self_use: Float32Array;
  soc: Float32Array;
  cost: Float32Array;
  revenue: Float32Array;
  band: Band[];
}

export const MONTH_NAMES = [
  'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
  'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
] as const;

/** First hour index of each month, plus a terminating 8760. */
export function monthBoundaries(): number[] {
  const out = [0];
  let h = 0;
  for (let m = 0; m < 12; m += 1) { h += (DAYS_IN_MONTH[m] ?? 0) * 24; out.push(h); }
  return out;
}

const sumRange = (a: Float32Array | undefined, from: number, to: number) => {
  if (!a) return 0;
  let t = 0;
  for (let i = from; i < to && i < a.length; i += 1) t += a[i] ?? 0;
  return t;
};

export interface MonthRow {
  month: string;
  /** kWh generated by the array. */
  generated: number;
  /** kWh consumed by the home. */
  consumed: number;
  /** kWh of generation used on site rather than exported. */
  selfUsed: number;
  /** kWh bought from the grid, for load AND for charging the battery. */
  imported: number;
  /** Of that import, the part that went into the battery for arbitrage. */
  importedToBattery: number;
  /** kWh sold to the grid. */
  exported: number;
  /** Euro paid for imported electricity, excluding the standing charge. */
  cost: number;
  /** Euro earned from export. */
  revenue: number;
  /** Share of consumption met without buying it, 0-1. */
  selfSufficiency: number;
  /** Share of generation kept on site rather than exported, 0-1. */
  selfConsumption: number;
}

/**
 * Month-by-month energy and money balance.
 *
 * Two subtleties make the naive arithmetic wrong, and both were wrong here
 * before this was written down:
 *
 * 1. `grid_import` is not only load. When a plan makes off-peak electricity
 *    cheap the dispatcher charges the battery FROM THE GRID, and that energy
 *    lands in `grid_import` too. Treating all import as load understates
 *    self-sufficiency, badly — by around a third on an arbitrage plan.
 *
 * 2. `battery_discharge` is energy leaving the pack, not energy reaching the
 *    load, and it may have come from the grid rather than the panels. Adding
 *    raw discharge to direct self-use both double-counts and mis-attributes.
 *
 * The dispatcher sends surplus to the battery before exporting, so the solar
 * share of charging in any hour is `min(charge, max(0, gen - cons))`, and the
 * remainder is grid-sourced. That identity is what the split below uses.
 */
export function monthlyBalance(sim: HourlySim): MonthRow[] {
  const b = monthBoundaries();
  const rows: MonthRow[] = [];
  for (let m = 0; m < 12; m += 1) {
    const from = b[m]!;
    const to = b[m + 1]!;
    const generated = sumRange(sim.gen, from, to);
    const consumed = sumRange(sim.cons, from, to);
    const imported = sumRange(sim.grid_import, from, to);
    const exported = sumRange(sim.grid_export, from, to);

    let gridCharge = 0;
    for (let i = from; i < to && i < HOURS_IN_YEAR; i += 1) {
      const charge = sim.battery_charge[i] ?? 0;
      if (charge <= 0) continue;
      const surplus = Math.max(0, (sim.gen[i] ?? 0) - (sim.cons[i] ?? 0));
      gridCharge += Math.max(0, charge - Math.min(charge, surplus));
    }

    // Generation that stayed on site. Whatever did not leave was used here,
    // whether directly, through the battery, or lost to round-trip losses.
    const selfUsed = Math.max(0, generated - exported);
    // Import that actually served demand, once battery charging is removed.
    const importForLoad = Math.max(0, imported - gridCharge);

    rows.push({
      month: MONTH_NAMES[m]!,
      generated, consumed, imported, exported, selfUsed,
      importedToBattery: gridCharge,
      cost: sumRange(sim.cost, from, to),
      revenue: sumRange(sim.revenue, from, to),
      selfSufficiency: consumed > 0
        ? Math.min(1, Math.max(0, (consumed - importForLoad) / consumed)) : 0,
      selfConsumption: generated > 0
        ? Math.min(1, Math.max(0, selfUsed / generated)) : 0,
    });
  }
  return rows;
}

export interface DayProfile {
  /** Day of year, 0-364. */
  dayIndex: number;
  label: string;
  /** 24 values each, kWh per hour. */
  generation: number[];
  consumption: number[];
  gridImport: number[];
  gridExport: number[];
  batteryCharge: number[];
  batteryDischarge: number[];
  /** Battery state of charge as a share of usable capacity, 0-1. */
  soc: number[];
  peakGeneration: number;
  peakConsumption: number;
  totalImported: number;
  totalExported: number;
}

/** Twenty-four hours of every series for one day of the year. */
export function dayProfile(
  sim: HourlySim,
  dayIndex: number,
  label: string,
  batteryCapacity = 0,
): DayProfile {
  const start = Math.max(0, Math.min(364, Math.floor(dayIndex))) * 24;
  const slice = (a: Float32Array | undefined) =>
    Array.from({ length: 24 }, (_, h) => (a?.[start + h] ?? 0));
  const generation = slice(sim.gen);
  const consumption = slice(sim.cons);
  const gridImport = slice(sim.grid_import);
  const gridExport = slice(sim.grid_export);
  return {
    dayIndex, label,
    generation, consumption, gridImport, gridExport,
    batteryCharge: slice(sim.battery_charge),
    batteryDischarge: slice(sim.battery_discharge),
    soc: batteryCapacity > 0
      ? slice(sim.soc).map((v) => Math.min(1, Math.max(0, v / batteryCapacity)))
      : new Array(24).fill(0),
    peakGeneration: Math.max(0, ...generation),
    peakConsumption: Math.max(0, ...consumption),
    totalImported: gridImport.reduce((a, v) => a + v, 0),
    totalExported: gridExport.reduce((a, v) => a + v, 0),
  };
}

/**
 * Representative days. The solstices bracket the year's extremes and the
 * equinoxes sit near its average, so four days describe the range a reader
 * will actually experience.
 */
export const REPRESENTATIVE_DAYS = [
  { dayIndex: 18, label: 'Mid-winter (19 January)' },
  { dayIndex: 79, label: 'Spring equinox (21 March)' },
  { dayIndex: 171, label: 'Mid-summer (21 June)' },
  { dayIndex: 264, label: 'Autumn equinox (22 September)' },
] as const;

export interface BandRow {
  band: Band;
  /** kWh imported while this band applied. */
  kwh: number;
  /** Euro paid for that energy. */
  cost: number;
  /** Hours of the year in this band. */
  hours: number;
  /** Effective price paid, euro/kWh. */
  effectiveRate: number;
}

/**
 * Import cost split by tariff band. This is the mechanism behind a
 * recommendation: a plan wins because of when the home draws power, and this
 * shows how much of the bill falls in each window.
 */
export function bandBreakdown(sim: HourlySim): BandRow[] {
  const acc = new Map<Band, { kwh: number; cost: number; hours: number }>();
  for (let i = 0; i < HOURS_IN_YEAR; i += 1) {
    const band = (sim.band?.[i] ?? 'day') as Band;
    const cur = acc.get(band) ?? { kwh: 0, cost: 0, hours: 0 };
    cur.kwh += sim.grid_import[i] ?? 0;
    cur.cost += sim.cost[i] ?? 0;
    cur.hours += 1;
    acc.set(band, cur);
  }
  return [...acc.entries()]
    .map(([band, v]) => ({
      band,
      kwh: v.kwh,
      cost: v.cost,
      hours: v.hours,
      effectiveRate: v.kwh > 0 ? v.cost / v.kwh : 0,
    }))
    .filter((r) => r.kwh > 0.5)
    .sort((a, b) => b.cost - a.cost);
}

export interface BatteryStats {
  capacity: number;
  /** kWh in and out across the year. */
  charged: number;
  discharged: number;
  /** Full equivalent cycles: throughput divided by usable capacity. */
  equivalentCycles: number;
  /** Round-trip efficiency actually achieved, 0-1. */
  roundTripEfficiency: number;
  /** Hours the battery sat at or near full, and at or near empty. */
  hoursFull: number;
  hoursEmpty: number;
  /** Share of the year the battery was doing nothing. */
  idleShare: number;
}

/**
 * How hard the battery actually works. A battery that is full for much of the
 * summer is oversized for the load; one that is empty every evening is
 * undersized. Both are visible here and nowhere else.
 */
export function batteryStats(sim: HourlySim, capacity: number): BatteryStats | null {
  if (!(capacity > 0)) return null;
  let charged = 0;
  let discharged = 0;
  let hoursFull = 0;
  let hoursEmpty = 0;
  let idle = 0;
  for (let i = 0; i < HOURS_IN_YEAR; i += 1) {
    const c = sim.battery_charge[i] ?? 0;
    const dch = sim.battery_discharge[i] ?? 0;
    charged += c;
    discharged += dch;
    if (c < 0.01 && dch < 0.01) idle += 1;
    const soc = (sim.soc?.[i] ?? 0) / capacity;
    if (soc >= 0.97) hoursFull += 1;
    if (soc <= 0.05) hoursEmpty += 1;
  }
  return {
    capacity,
    charged,
    discharged,
    equivalentCycles: discharged / capacity,
    roundTripEfficiency: charged > 0 ? discharged / charged : 0,
    hoursFull,
    hoursEmpty,
    idleShare: idle / HOURS_IN_YEAR,
  };
}

export interface YearSummary {
  generated: number;
  consumed: number;
  selfUsed: number;
  imported: number;
  exported: number;
  /** Share of consumption met without the grid, 0-1. */
  selfSufficiency: number;
  /** Share of generation kept at home, 0-1. */
  selfConsumption: number;
  /** Yield per kWp installed, kWh. */
  specificYield: number;
  /** Best and worst month by generation. */
  bestMonth: string;
  worstMonth: string;
  /** Ratio of best to worst month generation — the seasonal swing. */
  seasonalSwing: number;
}

export function yearSummary(rows: MonthRow[], kwp: number): YearSummary {
  const tot = (k: keyof MonthRow) => rows.reduce((a, r) => a + (r[k] as number), 0);
  const generated = tot('generated');
  const consumed = tot('consumed');
  // Only the part of import that served load counts against self-sufficiency.
  const imported = tot('imported') - tot('importedToBattery');
  const sorted = [...rows].sort((a, b) => b.generated - a.generated);
  const best = sorted[0];
  const worst = sorted[sorted.length - 1];
  return {
    generated,
    consumed,
    selfUsed: tot('selfUsed'),
    imported,
    exported: tot('exported'),
    selfSufficiency: consumed > 0 ? (consumed - imported) / consumed : 0,
    selfConsumption: generated > 0 ? tot('selfUsed') / generated : 0,
    specificYield: kwp > 0 ? generated / kwp : 0,
    bestMonth: best?.month ?? '—',
    worstMonth: worst?.month ?? '—',
    seasonalSwing: worst && worst.generated > 0 ? (best?.generated ?? 0) / worst.generated : 0,
  };
}

/**
 * Hours of the year sorted by import power, descending — a load duration
 * curve for grid draw. The shape says whether a bill is driven by a few
 * extreme hours or by a broad baseline, which is what decides whether a
 * time-of-use tariff can help at all.
 */
export function importDurationCurve(sim: HourlySim, buckets = 24): number[] {
  const sorted = Array.from(sim.grid_import).sort((a, b) => b - a);
  const out: number[] = [];
  const per = Math.floor(sorted.length / buckets);
  for (let i = 0; i < buckets; i += 1) {
    let t = 0;
    for (let j = i * per; j < (i + 1) * per; j += 1) t += sorted[j] ?? 0;
    out.push(per > 0 ? t / per : 0);
  }
  return out;
}

/** Share of annual import that falls in the most expensive N% of hours. */
export function peakConcentration(sim: HourlySim, topShare = 0.1): number {
  const costs: number[] = [];
  for (let i = 0; i < HOURS_IN_YEAR; i += 1) costs.push(sim.cost[i] ?? 0);
  const total = costs.reduce((a, v) => a + v, 0);
  if (total <= 0) return 0;
  costs.sort((a, b) => b - a);
  const n = Math.max(1, Math.floor(costs.length * topShare));
  let top = 0;
  for (let i = 0; i < n; i += 1) top += costs[i] ?? 0;
  return top / total;
}
